# See config.example.yml for documentation.
object_base: orig/GD7E70
object: sys/main.dol
hash: 20323bd58c8c87aa8234c9a36a82ced89773bb2c
symbols: config/GD7E70/symbols.txt
splits: config/GD7E70/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11